version: '3'
services: 

  mysql:
    build:
      dockerfile: './database/dockerfile'
      context: .
    container_name: database1
    restart: always
    environment:
      MYSQL_DATABASE: BITACORA
      MYSQL_USER: esau
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
    
  users:
    restart: always
    build:
      dockerfile: './users/dockerfile'
      context: .
    container_name: users
    ports:
      - "8081:80"
    links:
      - mysql
    
  registry:
    restart: always
    build: 
      dockerfile: './registry/dockerfile'
      context: .
    container_name: registry
    ports:
      - "8082:80"
    links:
      - mysql

  backend:
    restart: always
    build: 
      dockerfile: './backend/dockerfile'
      context: .
    container_name: backend
    links:
      - mysql