version: '3'
services: 

  mysql:
    build:
      dockerfile: './database/dockerfile'
      context: .
    container_name: database1
    restart: always
    environment:
      MYSQL_DATABASE: BITACORA
      MYSQL_USER: esau
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
    
  user:
    restart: always
    build:
      dockerfile: './user/dockerfile'
      context: .
    container_name: user
    links:
      - mysql
    
  registry:
    restart: always
    build: 
      dockerfile: './registry/dockerfile'
      context: .
    container_name: registry
    links:
      - mysql

  api:
    restart: always
    build: 
      dockerfile: './api/dockerfile'
      context: .
    container_name: api
    links:
      - mysql
    ports:
      - "8081:80"