SET time_zone = "America/Mexico_City";

DROP DATABASE IF EXISTS BITACORA;

CREATE DATABASE IF NOT EXISTS BITACORA;
USE BITACORA;

CREATE TABLE IF NOT EXISTS USUARIO( \
	ID INT(10) PRIMARY KEY AUTO_INCREMENT, \
	NOMBRE VARCHAR(150), \
	FINGER VARCHAR(150) \
);

CREATE TABLE IF NOT EXISTS REGISTRO( \
	ID INT(5) PRIMARY KEY AUTO_INCREMENT, \
	NOMBRE INT(10), \
	ENTRADA VARCHAR(150), \
	SALIDA VARCHAR(150), \
	CONSTRAINT `FK_USUARIO_REGISTRO` FOREIGN KEY (NOMBRE) REFERENCES USUARIO(ID) \
);

INSERT INTO USUARIO (NOMBRE,FINGER) \
VALUES ("CARLOS BALLARTA","CAR1");

INSERT INTO USUARIO (NOMBRE,FINGER) \
VALUES ("JENSEPIO","JEN2");

INSERT INTO USUARIO (NOMBRE,FINGER) \
VALUES ("COCO CELIS","COC3");

INSERT INTO USUARIO (NOMBRE,FINGER) \
VALUES ("FRAN HEVIA","FRA4");

INSERT INTO REGISTRO (NOMBRE,ENTRADA,SALIDA) VALUES (1,CURRENT_TIMESTAMP(),DATE_ADD(now() , INTERVAL 8 HOUR));

INSERT INTO REGISTRO (NOMBRE,ENTRADA,SALIDA) VALUES (2,CURRENT_TIMESTAMP(),DATE_ADD(now() , INTERVAL 8 HOUR));

INSERT INTO REGISTRO (NOMBRE,ENTRADA,SALIDA) VALUES (3,CURRENT_TIMESTAMP(),DATE_ADD(now() , INTERVAL 8 HOUR));

INSERT INTO REGISTRO (NOMBRE,ENTRADA,SALIDA) VALUES (4,CURRENT_TIMESTAMP(),DATE_ADD(now() , INTERVAL 8 HOUR));