FROM php:7.4-apache

	WORKDIR /var/www/html
	COPY ./users/files/ ./api/

	RUN chmod -R 755 api
	RUN chown -R www-data:www-data api

	WORKDIR /etc/apache2/sites-available/
	COPY ./users/api.conf .
	RUN a2ensite api.conf
	RUN service apache2 restart

	EXPOSE 80