FROM php:7.4-apache
	RUN docker-php-ext-install mysqli
	RUN apachectl restart

	WORKDIR /var/www/html
	COPY ./user/files/api_gw ./api_gw/

	RUN chmod -R 755 api_gw
	RUN chown -R www-data:www-data api_gw

	WORKDIR /etc/apache2/sites-available/
	COPY ./user/api_gw.conf .
	RUN a2ensite api_gw.conf
	RUN service apache2 restart

	EXPOSE 80